apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app-test
spec:
  selector:
    matchLabels:
      app: react-app-test
  replicas: 1
  template:
    metadata:
      labels:
        app: react-app-test
    spec:
      containers:
        - name: react-app-test
          image: REPOSITORY_TAG
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 50Mi
              cpu: 0.25