apiVersion: apps/v1
kind: Deployment
metadata:
  name: sri-test-react-app
  labels:
    app: sri-test-react-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sri-test-react-app
  template:
    metadata:
      labels:
        app: sri-test-react-app
    spec:
      containers:
        - name: sri-test-react-app
          image: 456840671316.dkr.ecr.us-east-1.amazonaws.com/sri-test-react-app:$GITHUB_SHA
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "50Mi"
              cpu: "250m"
        