apiVersion: apps/v1
kind: Deployment
metadata:
  name: sri-test-react-app
spec:
  selector:
    matchLabels:
      app: sri-test-react-app
  replicas: 1
  template:
    metadata:
      labels:
        app: sri-test-react-app
    spec:
      containers:
        - name: sri-test-react-app
          image: 456840671316.dkr.ecr.us-east-1.amazonaws.com/sri-test-react-app:1
          resources:
            requests:
              memory: 50Mi
              cpu: 0.25

---
apiVersion: v1
kind: Service
metadata:
  name: sri-test-react-app
spec:
  selector:
    app: sri-test-react-app
  ports:
    - name: http
      port: 80
  type: ClusterIP