apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app-test
  template:
    metadata:
      labels:
        app: react-app-test
    spec:
      containers:
        - name: react-app-test
          image: 456840671316.dkr.ecr.us-east-1.amazonaws.com/react-app-test:1.2
          ports:
            - containerPort: 80