name: Deploy to EKS

on: push
    

jobs:
  loginToAWS:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

        
  buildImage-and-Push-to-ECR:
     runs-on: ubuntu-latest
     needs:
       loginToAWS
         
     steps:

     - name: Code Checkout
       uses: actions/checkout@v4

     - name: Install kubectl
       uses: azure/setup-kubectl@v2.0
       with:
        version: 'v1.24.0' # default is latest stable
       id: install
     
     - name: Configure AWS credentials
       uses: aws-actions/configure-aws-credentials@v4
       with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

     - name: Login to Amazon ECR
       id: login-ecr
       uses: aws-actions/amazon-ecr-login@v1

     - name: Login to AWSECR
       uses: docker/login-action@v3
       with:
         registry: 456840671316.dkr.ecr.us-east-1.amazonaws.com
         username: ${{ secrets.AWS_ACCESS_KEY_ID }}
         password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
       env:
         aws-region: ${{ secrets.AWS_REGION }}

     - name: Build Image
       env:
         REGISTRY: 456840671316.dkr.ecr.us-east-1.amazonaws.com
         REPO: react-app-test
         REPOSITORY_TAG: ${REGISTRY}/${REPO}:latest
        
       run: | 
         docker build -t react-app-test .
         docker tag ${REPO}:latest ${REGISTRY}/${REPO}:latest
         docker push ${REGISTRY}/${REPO}:latest

  deployToCluster:
      runs-on: ubuntu-latest
      needs: buildImage-and-Push-to-ECR
      steps:
      
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Configure kubectl
        env:
          KUBECONFIG: ${{ runner.temp }}/kubeconfig
        run: |
          aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }} --kubeconfig $KUBECONFIG
          echo "KUBECONFIG=$KUBECONFIG" >> $GITHUB_ENV
    
      - name: Deploy to EKS
        run: |
          kubectl apply -f ./deploy.yaml


    