name: Deploy react app to EKS cluster
on:
  push:
    branches: [ "main" ]

jobs:
  loginToAws:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

  DeployToEKS:
    runs-on: ubuntu-latest
    needs: loginToAws
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install kubectl
      uses: azure/setup-kubectl@v2.0
      with:
        version: 'v1.24.0' # default is latest stable
      id: install

    - name: Log in to AWS ECR
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.AWS_ECR }}
        username: ${{ secrets.AWS_ACCESS_KEY_ID }}
        password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      env:
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Build Docker image
      env:
        REGISTRY: 456840671316.dkr.ecr.us-east-1.amazonaws.com
        REPO: sri-test-react-app
        REPOSITORY_TAG: ${REGISTRY}/${REPO}:${GITHUB_SHA}
        
      run: |
        docker build -t ${REPO} .
        docker tag ${REPO}:latest ${REGISTRY}/${REPO}:${GITHUB_SHA}
        docker push ${REGISTRY}/${REPO}:${GITHUB_SHA}

    - name: Download kubeconfig file
      run: |
        aws eks update-kubeconfig --name sri-test-react-app
        echo "Kubeconfig file downloaded successfully."

    - name: Deploy to EKS
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml

      
    

