name: Deploy react app to EKS cluster
on:
  push:
    branches: [ "main" ]

jobs:
# This job Installs kubectl, which is required to interact with the EKS cluster

  install_Kubectl:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install kubectl
      uses: azure/setup-kubectl@v4
      with:
        version: 'latest'
      id: install

# This job builds the Docker image and pushes it to AWS ECR

  buildAndPushDockerImage:
    runs-on: ubuntu-latest
    needs: install_Kubectl
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push docker image to Amazon ECR
      env:
        REGISTRY: 456840671316.dkr.ecr.us-east-1.amazonaws.com
        REPOSITORY: react-app-test
        IMAGE_TAG: ${GITHUB_RUN_NUMBER}
      run: |
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

    - name: Update kube config
      run: aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}

    # This job deploys the application to the EKS cluster
    - name: Deploy to EKS
      run: |
        sed -i "s|image: REPOSITORY_TAG|image: 456840671316.dkr.ecr.us-east-1.amazonaws.com/react-app-test:$GITHUB_RUN_NUMBER|g" ./deploy.yaml
        kubectl apply -f ./deploy.yaml
        kubectl apply -f ./service.yaml